function n_var = calnoisev(alpha,theta,psi,phi,d1,tdoa,vprev,c,deltaQ,deltaw,Qprev,wprev,alphav,thetav,psiv,phiv,d1v,tdoav)

P = length(vprev);
sys1v = [];
sys2v = [];
sys3v = [];
sys4v = [];
sys5v = [];

for indp = 2:P
    sys = psiv^2*(cos(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) ...
        - deltaQ*sin(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 ...
        + phiv^2*(sin(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) ...
        + deltaQ*cos(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 ...
        + tdoav^2*(c*sin(Qprev + psi(indp))*cos(phi(indp) + wprev) ...
        + c*deltaQ*cos(Qprev + psi(indp))*cos(phi(indp) + wprev))^2 ...
        + d1v^2*(deltaQ*(cos(Qprev + psi(1))*cos(phi(1) + wprev) ...
        - cos(Qprev + psi(indp))*cos(phi(indp) + wprev)) + sin(Qprev + psi(1))*cos(phi(1) + wprev) ...
        - sin(Qprev + psi(indp))*cos(phi(indp) + wprev))^2 + psiv^2*(cos(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)) ...
        - deltaQ*sin(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)))^2 ...
        + phiv^2*(sin(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)) ...
        + deltaQ*cos(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)))^2 ...
        + alphav^2*vprev(1)^2*cos(alpha(1))^2*cos(theta(1))^2 + alphav^2*vprev(indp)^2*cos(alpha(1))^2*cos(theta(indp))^2 ...
        + thetav^2*vprev(1)^2*sin(alpha(1))^2*sin(theta(1))^2 + thetav^2*vprev(indp)^2*sin(alpha(1))^2*sin(theta(indp))^2;
    sys1v = [sys1v; sys];
end

for indp = 2:P
    sys = phiv^2*(sin(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) ...
        + deltaQ*cos(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 ...
        + psiv^2*(cos(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) ...
        - deltaQ*sin(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 ...
        + tdoav^2*(c*sin(Qprev + psi(indp))*sin(phi(indp) + wprev) + c*deltaQ*cos(Qprev + psi(indp))*sin(phi(indp) + wprev))^2 ...
        + d1v^2*(deltaQ*(cos(Qprev + psi(1))*sin(phi(1) + wprev) - cos(Qprev + psi(indp))*sin(phi(indp) + wprev)) ...
        + sin(Qprev + psi(1))*sin(phi(1) + wprev) - sin(Qprev + psi(indp))*sin(phi(indp) + wprev))^2 ...
        + phiv^2*(sin(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)) ...
        + deltaQ*cos(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)))^2 ...
        + psiv^2*(cos(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)) ...
        - deltaQ*sin(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)))^2 ...
        + alphav^2*vprev(1)^2*cos(alpha(1))^2*sin(theta(1))^2 ...
        + alphav^2*vprev(indp)^2*cos(alpha(1))^2*sin(theta(indp))^2 + thetav^2*vprev(1)^2*sin(alpha(1))^2*cos(theta(1))^2 ...
        + thetav^2*vprev(indp)^2*sin(alpha(1))^2*cos(theta(indp))^2;
    sys2v = [sys2v; sys];
end
 
for indp = 2:P
    sys = psiv^2*(sin(Qprev + psi(1))*(d1 - vprev(1)) + deltaQ*cos(Qprev + psi(1))*(d1 - vprev(1)))^2 ...
        + psiv^2*(sin(Qprev + psi(indp))*(d1 - vprev(indp) + c*tdoa(indp)) ...
        + deltaQ*cos(Qprev + psi(indp))*(d1 - vprev(indp) + c*tdoa(indp)))^2 ...
        + tdoav^2*(c*cos(Qprev + psi(indp)) - c*deltaQ*sin(Qprev + psi(indp)))^2 + d1v^2*(cos(Qprev + psi(indp)) ...
        - cos(Qprev + psi(1)) + deltaQ*(sin(Qprev + psi(1)) ...
        - sin(Qprev + psi(indp))))^2 + alphav^2*vprev(1)^2*sin(alpha(1))^2 ...
        + alphav^2*vprev(indp)^2*sin(alpha(1))^2;
    sys3v = [sys3v; sys];
end
 
for indp = 2:P
    sys = psiv^2*(cos(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) ...
        - deltaw*cos(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^ ...
        + phiv^2*(sin(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) ...
        + deltaw*sin(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 + tdoav^2*(c*sin(Qprev + psi(indp))*cos(phi(indp) + wprev) - c*deltaw*sin(Qprev + psi(indp))*sin(phi(indp) + wprev))^2 + d1v^2*(deltaw*(sin(Qprev + psi(1))*sin(phi(1) + wprev) - sin(Qprev + psi(indp))*sin(phi(indp) + wprev)) - sin(Qprev + psi(1))*cos(phi(1) + wprev) + sin(Qprev + psi(indp))*cos(phi(indp) + wprev))^2 + psiv^2*(cos(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)) - deltaw*cos(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)))^2 + phiv^2*(sin(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)) + deltaw*sin(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)))^2 + alphav^2*vprev(1)^2*cos(alpha(1))^2*cos(theta(1))^2 + alphav^2*vprev(indp)^2*cos(alpha(1))^2*cos(theta(indp))^2 + thetav^2*vprev(1)^2*sin(alpha(1))^2*sin(theta(1))^2 + thetav^2*vprev(indp)^2*sin(alpha(1))^2*sin(theta(indp))^2;
    sys4v = [sys4v; sys];
end
 
for indp = 2:P
    sys = psiv^2*(cos(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) - deltaw*cos(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 + phiv^2*(sin(Qprev + psi(indp))*sin(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)) + deltaw*sin(Qprev + psi(indp))*cos(phi(indp) + wprev)*(d1 - vprev(indp) + c*tdoa(indp)))^2 + tdoav^2*(c*sin(Qprev + psi(indp))*cos(phi(indp) + wprev) - c*deltaw*sin(Qprev + psi(indp))*sin(phi(indp) + wprev))^2 + d1v^2*(deltaw*(sin(Qprev + psi(1))*sin(phi(1) + wprev) - sin(Qprev + psi(indp))*sin(phi(indp) + wprev)) - sin(Qprev + psi(1))*cos(phi(1) + wprev) + sin(Qprev + psi(indp))*cos(phi(indp) + wprev))^2 + psiv^2*(cos(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)) - deltaw*cos(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)))^2 + phiv^2*(sin(Qprev + psi(1))*sin(phi(1) + wprev)*(d1 - vprev(1)) + deltaw*sin(Qprev + psi(1))*cos(phi(1) + wprev)*(d1 - vprev(1)))^2 + alphav^2*vprev(1)^2*cos(alpha(1))^2*cos(theta(1))^2 + alphav^2*vprev(indp)^2*cos(alpha(1))^2*cos(theta(indp))^2 + thetav^2*vprev(1)^2*sin(alpha(1))^2*sin(theta(1))^2 + thetav^2*vprev(indp)^2*sin(alpha(1))^2*sin(theta(indp))^2;
    sys5v = [sys5v; sys];
end

n_var = [sys1v; sys2v; sys3v; sys4v; sys5v];
end