
syms alpha1 theta1 psi1 phi1 alphap thetap psip phip tdoa Qprev wprev d1 vprev1 vprevp c deltaQ deltaw
syms alphav thetav psiv phiv d1v tdoav
syms sys1v sys2v sys3v sys4v sys5v

Q_asin = (-vprev1+d1)*cos(psi1+Qprev)*cos(phi1+wprev)+(vprevp-d1-c*tdoa)*cos(psip+Qprev)*cos(phip+wprev);
Q_acos = (-vprev1+d1)*cos(psi1+Qprev)*sin(phi1+wprev)+(vprevp-d1-c*tdoa)*cos(psip+Qprev)*sin(phip+wprev);
Q_aelev = (vprev1-d1)*sin(psi1+Qprev)+(-vprevp+d1+c*tdoa)*sin(psip+Qprev);
w_asin = (vprev1-d1)*sin(psi1+Qprev)*sin(phi1+wprev)+(-vprevp+d1+c*tdoa)*sin(psip+Qprev)*sin(phip+wprev);
w_acos = (-vprev1+d1)*sin(psi1+Qprev)*cos(phi1+wprev)+(vprevp-d1-c*tdoa)*sin(psip+Qprev)*cos(phip+wprev);

Q_bsin = (vprev1-d1)*sin(psi1+Qprev)*cos(phi1+wprev)+(-vprevp+d1+c*tdoa)*sin(psip+Qprev)*cos(phip+wprev)+vprev1*sin(alpha1)*cos(theta1)-vprevp*sin(alphap)*cos(thetap);
Q_bcos = (vprev1-d1)*sin(psi1+Qprev)*sin(phi1+wprev)+(-vprevp+d1+c*tdoa)*sin(psip+Qprev)*sin(phip+wprev)+vprev1*sin(alpha1)*sin(theta1)-vprevp*sin(alphap)*sin(thetap);
Q_belev = (vprev1-d1)*cos(psi1+Qprev)+(-vprevp+d1+c*tdoa)*cos(psip+Qprev)+vprev1*cos(alpha1)-vprevp*cos(alphap);
w_bsin = (vprev1-d1)*sin(psi1+Qprev)*cos(phi1+wprev)+(-vprevp+d1+c*tdoa)*sin(psip+Qprev)*cos(phip+wprev)+vprev1*sin(alpha1)*cos(theta1)-vprevp*sin(alphap)*cos(thetap);
w_bcos = (vprev1-d1)*sin(psi1+Qprev)*sin(phi1+wprev)+(-vprevp+d1+c*tdoa)*sin(psip+Qprev)*sin(phip+wprev)+vprev1*sin(alpha1)*sin(theta1)-vprevp*sin(alphap)*sin(thetap);

sys1v = (diff(Q_bsin,alpha1)-deltaQ*diff(Q_asin,alpha1))^2*alphav^2 ...
+(diff(Q_bsin,theta1)-deltaQ*diff(Q_asin,theta1))^2*thetav^2 ...
+(diff(Q_bsin,psi1)-deltaQ*diff(Q_asin,psi1))^2*psiv^2 ...
+(diff(Q_bsin,phi1)-deltaQ*diff(Q_asin,phi1))^2*phiv^2 ...
+(diff(Q_bsin,d1)-deltaQ*diff(Q_asin,d1))^2*d1v^2 ...
+(diff(Q_bsin,tdoa)-deltaQ*diff(Q_asin,tdoa))^2*tdoav^2 ...
+(diff(Q_bsin,alphap)-deltaQ*diff(Q_asin,alphap))^2*alphav^2 ...
+(diff(Q_bsin,thetap)-deltaQ*diff(Q_asin,thetap))^2*thetav^2 ...
+(diff(Q_bsin,psip)-deltaQ*diff(Q_asin,psip))^2*psiv^2 ...
+(diff(Q_bsin,phip)-deltaQ*diff(Q_asin,phip))^2*phiv^2

sys2v = (diff(Q_bcos,alpha1)-deltaQ*diff(Q_acos,alpha1))^2*alphav^2 ...
+(diff(Q_bcos,theta1)-deltaQ*diff(Q_acos,theta1))^2*thetav^2 ...
+(diff(Q_bcos,psi1)-deltaQ*diff(Q_acos,psi1))^2*psiv^2 ...
+(diff(Q_bcos,phi1)-deltaQ*diff(Q_acos,phi1))^2*phiv^2 ...
+(diff(Q_bcos,d1)-deltaQ*diff(Q_acos,d1))^2*d1v^2 ...
+(diff(Q_bcos,tdoa)-deltaQ*diff(Q_acos,tdoa))^2*tdoav^2 ...
+(diff(Q_bcos,alphap)-deltaQ*diff(Q_acos,alphap))^2*alphav^2 ...
+(diff(Q_bcos,thetap)-deltaQ*diff(Q_acos,thetap))^2*thetav^2 ...
+(diff(Q_bcos,psip)-deltaQ*diff(Q_acos,psip))^2*psiv^2 ...
+(diff(Q_bcos,phip)-deltaQ*diff(Q_acos,phip))^2*phiv^2

sys3v = (diff(Q_belev,alpha1)-deltaQ*diff(Q_aelev,alpha1))^2*alphav^2 ...
+(diff(Q_belev,theta1)-deltaQ*diff(Q_aelev,theta1))^2*thetav^2 ...
+(diff(Q_belev,psi1)-deltaQ*diff(Q_aelev,psi1))^2*psiv^2 ...
+(diff(Q_belev,phi1)-deltaQ*diff(Q_aelev,phi1))^2*phiv^2 ...
+(diff(Q_belev,d1)-deltaQ*diff(Q_aelev,d1))^2*d1v^2 ...
+(diff(Q_belev,tdoa)-deltaQ*diff(Q_aelev,tdoa))^2*tdoav^2 ...
+(diff(Q_belev,alphap)-deltaQ*diff(Q_aelev,alphap))^2*alphav^2 ...
+(diff(Q_belev,thetap)-deltaQ*diff(Q_aelev,thetap))^2*thetav^2 ...
+(diff(Q_belev,psip)-deltaQ*diff(Q_aelev,psip))^2*psiv^2 ...
+(diff(Q_belev,phip)-deltaQ*diff(Q_aelev,phip))^2*phiv^2

sys4v = (diff(w_bsin,alpha1)-deltaw*diff(w_asin,alpha1))^2*alphav^2 ...
+(diff(w_bsin,theta1)-deltaw*diff(w_asin,theta1))^2*thetav^2 ...
+(diff(w_bsin,psi1)-deltaw*diff(w_asin,psi1))^2*psiv^2 ...
+(diff(w_bsin,phi1)-deltaw*diff(w_asin,phi1))^2*phiv^2 ...
+(diff(w_bsin,d1)-deltaw*diff(w_asin,d1))^2*d1v^2 ...
+(diff(w_bsin,tdoa)-deltaw*diff(w_asin,tdoa))^2*tdoav^2 ...
+(diff(w_bsin,alphap)-deltaw*diff(w_asin,alphap))^2*alphav^2 ...
+(diff(w_bsin,thetap)-deltaw*diff(w_asin,thetap))^2*thetav^2 ...
+(diff(w_bsin,psip)-deltaw*diff(w_asin,psip))^2*psiv^2 ...
+(diff(w_bsin,phip)-deltaw*diff(w_asin,phip))^2*phiv^2

sys5v = (diff(w_bsin,alpha1)-deltaw*diff(w_asin,alpha1))^2*alphav^2 ...
+(diff(w_bsin,theta1)-deltaw*diff(w_asin,theta1))^2*thetav^2 ...
+(diff(w_bsin,psi1)-deltaw*diff(w_asin,psi1))^2*psiv^2 ...
+(diff(w_bsin,phi1)-deltaw*diff(w_asin,phi1))^2*phiv^2 ...
+(diff(w_bsin,d1)-deltaw*diff(w_asin,d1))^2*d1v^2 ...
+(diff(w_bsin,tdoa)-deltaw*diff(w_asin,tdoa))^2*tdoav^2 ...
+(diff(w_bsin,alphap)-deltaw*diff(w_asin,alphap))^2*alphav^2 ...
+(diff(w_bsin,thetap)-deltaw*diff(w_asin,thetap))^2*thetav^2 ...
+(diff(w_bsin,psip)-deltaw*diff(w_asin,psip))^2*psiv^2 ...
+(diff(w_bsin,phip)-deltaw*diff(w_asin,phip))^2*phiv^2